"""add converted_pptx_path and conversion_status to files

Revision ID: e27d2e61d58d
Revises: 36dbe87f8e7e
Create Date: 2025-05-18 11:56:09.573172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27d2e61d58d'
down_revision: Union[str, None] = '36dbe87f8e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('converted_pptx_path', sa.String(), nullable=True))
    op.add_column('files', sa.Column('conversion_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'conversion_status')
    op.drop_column('files', 'converted_pptx_path')
    # ### end Alembic commands ###
